Use pytest to run doctests
Invoking the tests using `python -m doctest` causes the parent directory
of the file under test to be added to `syspath`. As it happens this
contains a file called `csv.py`. When the module attempts to import Pandas
(via one of transitive imports) it blows up with:

    ImportError: cannot import name 'QUOTE_NONNUMERIC' from 'csv'

Good times.