fix: Catch Trino exception for overly complex queries generated by hypothesis
Generative tests failed with a cryptic trino error:
https://github.com/opensafely-core/ehrql/actions/runs/6117284557/job/16603681004

sqlalchemy.exc.DBAPIError: (trino.exceptions.TrinoQueryError) TrinoQueryError(type=INTERNAL_ERROR, name=GENERIC_INTERNAL_ERROR, message="io.airlift.bytecode.CompilationException: Error compiling class: io/trino/$gen/JoinFilterFunction_20230908_040709_2725", query_id=20230908_040455_07578_2uerr)

The most simplified version of this query that I could produce involved
multiple nested horizonatal aggregations of strings
(MaximumOf/MinimumOf) and a StringContains. Arbitrarily simplifying
small parts of the query would allow it to pass, so the error appears to
be related to the nestedness or complexity of the query, although not
one that trino catches in any user-friendly way.