fix: Move population validation
Raising the error from `compile` means that the user gets a traceback
with our code in it, whereas we want them to see just the error message.

Previously the error looked like:
```
Traceback (most recent call last):
  File "/home/dave/.virtualenvs/ebm-databuilder/bin/databuilder", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/home/dave/projects/ebmdatalab/databuilder/databuilder/__main__.py", line 35, in entrypoint
    return main(sys.argv[1:], environ=os.environ)  # pragma: no cover
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/projects/ebmdatalab/databuilder/databuilder/__main__.py", line 75, in main
    function(**kwargs)
  File "/home/dave/projects/ebmdatalab/databuilder/databuilder/main.py", line 42, in generate_dataset
    variable_definitions = compile(dataset_definition)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/projects/ebmdatalab/databuilder/databuilder/query_language.py", line 80, in compile
    raise AttributeError(
AttributeError: A population has not been defined; define one with define_population()
```

Now it looks like:
```
A population has not been defined; define one with define_population()
```

I also realised that we didn't have unit tests covering
`load_dataset_definition` (though obviously it must have been covered
elsewhere) so I've added some.